# Generated by Django 5.2.17 on 2026-10-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_band', models.CharField(choices=[('12-17', '12-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-49', '35-49'), ('50-64', '50-64'), ('65+', '65+')], max_length=8)),
                ('marital', models.CharField(max_length=16)),
                ('education', models.CharField(max_length=16)),
                ('std', models.CharField(max_length=3)),
                ('tested_past_year', models.CharField(max_length=3)),
                ('aids_education', models.CharField(max_length=3)),
                ('place', models.CharField(max_length=16)),
                ('drugs', models.CharField(max_length=3)),
                ('score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
